# Render deployment configuration
services:
  # Worker service: runs tracker in background
  - type: worker
    name: gaming-tracker-worker
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    startCommand: npm start
    envVars:
      - key: DOCKER_ENV
        value: "True"
      - key: HEADLESS_MODE
        value: "true"
      # add all your other secrets from your .env
    autoDeploy: true

  # Web service: runs web UI to control tracker
  - type: web
    name: gaming-tracker-ui
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    startCommand: npm run web
    envVars:
      - key: DOCKER_ENV
        value: "True"
      - key: HEADLESS_MODE
        value: "true"
      # add all your other secrets from your .env
    autoDeploy: true
