services:
  - type: web
    name: gaming-tracker
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DOCKER_ENV
        value: "True"
      - key: HEADLESS_MODE
        value: "true"
      - key: SERVER_PORT
        value: "3000"
      # Add all your other secrets here (Render secret envs)
      # GOOGLE_PRIVATE_KEY, PDL_API_KEY, SLACK_TOKEN, GMAIL_APP_PASSWORD, etc.
    autoDeploy: true
    healthCheckPath: /health
    instanceCount: 1
